@host = localhost:3000/api


### get all users
GET http://{{host}}/users

### get single user
GET http://{{host}}/users/test1

### creat user
POST http://{{host}}/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "test333",
    "password": "123"
}